### ISSUE TITLE
Unable to use S3 for binarystore

### ISSUE THREAD

**Issue by bodgit** [fervidus/artifactory#17]
I would like to be able to configure the binarystore to use S3. Ultimately I want to use the Amazon S3 SDK Cluster Binary Provider so I need to be able to set binarystore.xml to something like this:
```
<config version="2">
    <chain template="cluster-s3-storage-v3"/>
    <provider id="s3-storage-v3" type="s3-storage-v3">
       <endpoint>http://s3.amazonaws.com</endpoint>
       <bucketName>bucketName</bucketName>
       <path>pathPrefix</path>
       <region>s3Region</region>
       <identity>yourIdentity</identity>
       <credential>yourCredentials</credential>
       <usePresigning>true</usePresigning>
       <signatureExpirySeconds>600</signatureExpirySeconds>
   </provider>
</config>
```
However the module should be updated to allow any of the valid S3 configurations.

**Comment by mojibake-umd** [comment]
I thought I should mention that S3 binarystore is only available to paid Artifactory,
in case you are attempting to use without a paid license.

Let me know if you need help on overriding the binarystore.xml config with a collector, in your puppet configuration, until issue can be addressed.

**Comment by bodgit** [comment]
I have a paid license for Artifactory Enterprise so I'm in the process of upgrading the current Pro install. However I've got to deal with the version 6 -> 7 upgrade piece first before I can migrate the storage to S3.

How do you propose  overriding the configuration in the interim?

**Comment by mojibake-umd** [comment]
If you have some wrapper puppet module like we use to setup the system and include the artifactory class.
You can add a file resource collect like below to override what the artifactory class would put out.

  File<| title == "${artifactory::artifactory_home}/etc/artifactory/binarystore.xml" |>{
    content => files ('artifactory_wrapper_module/binarystore.xml'),
  }

#artifactory_wrapper_module/files/binarystore.xml

<config version="2">
    <chain template="cluster-s3-storage-v3"/>
    <provider id="s3-storage-v3" type="s3-storage-v3">
       <endpoint>http://s3.amazonaws.com</endpoint>
       <bucketName>bucketName</bucketName>
       <path>pathPrefix</path>
       <region>s3Region</region>
       <identity>yourIdentity</identity>
       <credential>yourCredentials</credential>
       <usePresigning>true</usePresigning>
       <signatureExpirySeconds>600</signatureExpirySeconds>
   </provider>
</config>

**Comment by bodgit** [comment]
I have a `profile::artifactory` class that sets up the Apache vhost amongst other things. I'll add it there for now, thanks.
